namespace: dev1

resources:
  - ../../base

namePrefix: dev1-

patches:
  - target:
      kind: Ingress
      name: staging-daskal-ai-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev1-daskal-ai-ingress
      - op: replace
        path: /spec/rules/0/host
        value: dev1.daskal.ai
  - target:
      kind: Service
      name: daskal-ai-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev1-daskal-ai-service
  - target:
      kind: Deployment
      name: daskal-ai-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev1-daskal-ai-deployment
      - op: replace
        path: /spec/selector/matchLabels/app
        value: dev1-daskal-ai-pod
      - op: replace
        path: /spec/template/metadata/labels/app
        value: dev1-daskal-ai-pod
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: dev1-daskal-ai-data-pvc
  - target:
      kind: PersistentVolumeClaim
      name: daskal-ai-data-pvc
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev1-daskal-ai-data-pvc
